"""
Profit Machine v10 - Adapter for Master Controller
"""

import sys
import os
from pathlib import Path

# Add the original v10 code directory
v10_original_path = Path(__file__).parent.parent / 'v10_original'
sys.path.insert(0, str(v10_original_path))

try:
    # Try to import your original v10 code
    from profit_machine_v10 import ProfitMachineV10 as OriginalV10
    V10_AVAILABLE = True
except ImportError:
    V10_AVAILABLE = False
    print("⚠️  Original v10 code not found. Using stub.")

class ProfitMachineV10:
    """Adapter for original v10 engine"""
    
    def __init__(self, config_file='config_v10.json'):
        if V10_AVAILABLE:
            # Initialize original v10
            config_path = Path(__file__).parent / config_file
            self.engine = OriginalV10(config_path)
        else:
            # Fallback to stub
            self.engine = V10Stub()
        
        print("✅ v10 Engine Initialized")
    
    def execute_daily_run(self) -> dict:
        """Execute v10 daily run"""
        return self.engine.execute_daily_run()
    
    def generate_article(self, topic: str = None, category: str = None) -> dict:
        """Generate article (for master controller)"""
        
        if hasattr(self.engine, 'generate_article'):
            return self.engine.generate_article(topic, category)
        else:
            # Fallback to execute_daily_run with topic override
            result = self.execute_daily_run()
            
            # Extract article data
            return {
                'success': result.get('success', False),
                'topic': result.get('topic_data', {}).get('topic', 'Unknown'),
                'category': result.get('topic_data', {}).get('category', 'general'),
                'content': result.get('article_content', ''),
                'word_count': result.get('article_info', {}).get('word_count', 0),
                'images_count': result.get('article_info', {}).get('images_count', 0),
                'revenue_estimate': result.get('revenue_estimate', {}).get('monthly_estimate', 0),
                'article_id': result.get('article_id', 0)
            }
    
    def get_stats(self) -> dict:
        """Get v10 statistics"""
        if hasattr(self.engine, 'get_statistics'):
            return self.engine.get_statistics()
        else:
            return {'status': 'v10 statistics not available'}

class V10Stub:
    """Stub for v10 when original code is not available"""
    
    def __init__(self):
        print("⚠️  Using v10 stub - no actual v10 code")
    
    def execute_daily_run(self) -> dict:
        """Stub execute method"""
        
        import random
        from datetime import datetime
        
        topics = [
            "How to Make Money Online",
            "Affiliate Marketing Guide",
            "Passive Income Strategies",
            "Blogging for Beginners",
            "Digital Marketing Tips"
        ]
        
        return {
            'success': True,
            'timestamp': datetime.now().isoformat(),
            'topic_data': {
                'topic': random.choice(topics),
                'category': random.choice(['business', 'finance', 'technology']),
                'profit_potential': 'High'
            },
            'article_info': {
                'word_count': random.randint(1500, 2500),
                'images_count': random.randint(3, 5),
                'affiliate_links_count': random.randint(2, 4)
            },
            'revenue_estimate': {
                'monthly_estimate': round(random.uniform(30, 100), 2)
            },
            'article_id': random.randint(1000, 9999),
            'article_content': f"<h1>Sample Article</h1><p>This is a sample article generated by v10 stub.</p>"
        }
    
    def generate_article(self, topic: str = None, category: str = None) -> dict:
        """Stub generate method"""
        
        result = self.execute_daily_run()
        
        if topic:
            result['topic_data']['topic'] = topic
        
        if category:
            result['topic_data']['category'] = category
        
        return result
